<?php

namespace vdmBundle\Repository;

/**
 * VdmClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VdmClassRepository extends \Doctrine\ORM\EntityRepository
{
}
