vdmclass_index:
    path:     /
    defaults: { _controller: "vdmBundle:VdmClass:index" }
    methods:  GET

vdmclass_show:
    path:     /{id}/show
    defaults: { _controller: "vdmBundle:VdmClass:show" }
    methods:  GET

vdmclass_new:
    path:     /new
    defaults: { _controller: "vdmBundle:VdmClass:new" }
    methods:  [GET, POST]

vdmclass_edit:
    path:     /{id}/edit
    defaults: { _controller: "vdmBundle:VdmClass:edit" }
    methods:  [GET, POST]

vdmclass_delete:
    path:     /{id}/delete
    defaults: { _controller: "vdmBundle:VdmClass:delete" }
    methods:  DELETE
